<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <RootNamespace>TruthCardGame.Core</RootNamespace>
    <AssemblyName>Game.Core</AssemblyName>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\Assets\Scripts\Portable\Game.Core\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Game.Content\Game.Content.csproj" />
  </ItemGroup>

</Project>
