<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <RootNamespace>TruthCardGame.Content.Sqlite</RootNamespace>
    <AssemblyName>Game.Content.Sqlite</AssemblyName>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Game.Content\Game.Content.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="SQLITE-SCHEMA-V1.sql" />
  </ItemGroup>

</Project>
