<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>TruthCardGame.Content.Json</RootNamespace>
    <AssemblyName>Game.Content.Json</AssemblyName>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Game.Content\Game.Content.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\TestData\**\*.json" CopyToOutputDirectory="PreserveNewest" Link="TestData\%(Filename)%(Extension)" />
  </ItemGroup>

</Project>
