<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <RootNamespace>TruthCardGame.Content</RootNamespace>
    <AssemblyName>Game.Content</AssemblyName>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\Assets\Scripts\Portable\Game.Content\**\*.cs" />
  </ItemGroup>

</Project>
